export enum PRODUCT_CATEGORIES {
  OBST = 'obst',
  GEMUESE = 'gemuese',
  FRISCHE = 'frische',
  TIEFKUEHL = 'tiefkuehl',
  SUESSES = 'suesses',
  TEE = 'tee',
  GETRAENKE = 'getraenke',
  DROGERIE = 'drogerie',
  HAUSHALT = 'haushalt',
  TIER = 'tier',
  NUDELN = 'nudeln',
  BACKEN = 'backen',
  MUESLI = 'muesli',
  FRUEHSTUECK = 'fruehstueck',
  KONSERVEN = 'konserven',
  OEL = 'oel',
  FLEISCH = 'fleisch',
  GEWUERZE = 'gewuerze',
}
